retail_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_HOST', 'localhost') }}"
      user: "{{ env_var('POSTGRES_USER', 'retail') }}"
      password: "{{ env_var('POSTGRES_PASSWORD', 'retail') }}"
      port: "{{ env_var('POSTGRES_PORT', '5432') | int }}"
      dbname: "{{ env_var('POSTGRES_DB', 'retail') }}"
      schema: "gold"
      threads: 4
      connect_timeout: 10
