version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: retail_pg
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d   # <- tes scripts d'init auto
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: retail_pgadmin
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pg_data:
